apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: radar
  labels:
    app: dtradar
spec:
  selector:
    matchLabels:
      app: dtradar
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: dtradar
        tier: frontend
    spec:
      containers:
      - name: dtradar
        image: serdarkalayci/dtradar:2018.12.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80